image: node:19.5.0

pages:
    stage: deploy
    before_script:
        - npm ci
    script:
        - npm run build
        - rm -rf public
        - cp -r dist public
    artifacts:
        paths:
            - public
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

stages:
    - test
    - build
    - deploy

code_quality:
    image: node:19.5.0
    stage: test
    before_script:
        - npm ci
    script:
        - npm run lint
    only:
        - merge_requests

build:
    image: node:19.5.0
    stage: build
    before_script:
        - echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> .env
        - npm ci
    script:
        - npm run build
        - rm .env
    artifacts:
        paths:
            - dist
    only:
        - merge_requests
        - master

deploy:
    image: alpine:latest
    stage: deploy
    before_script:
        - apk update && apk add rsync openssh
        - mkdir ~/.ssh
        - chmod 600 ~/.ssh
        - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa
        - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
        - chmod 600 ~/.ssh/known_hosts
    environment:
        name: production
    resource_group: production
    script:
        - rsync -a --delete dist/ alex@135.181.80.44:/home/alex/repository-gallery
    only:
        - merge_requests
        - master
